rcv_to_sub={"1 Cor.": "1 Cor.",
"1 John": "1 Jn.",
"1 Pet.": "1 Pet.",
"1 Thes.": "1 Th.",
"1 Tim.": "1 Tim.",
"2 Cor.": "2 Cor.",
"2 John": "2 Jn.",
"2 Pet.": "2 Pet.",
"2 Thes.": "2 Th.",
"2 Tim.": "2 Tim.",
"3 John": "3 Jn.",
"Acts": "Acts",
"Col.": "Col.",
"Eph.": "Eph.",
"Gal.": "Gal.",
"Heb.": "Heb.",
"James": "Jas.",
"John": "Jn.",
"Jude": "Jude.",
"Luke": "Lk.",
"Mark": "Mk.",
"Matt.": "Mt.",
"Phil.": "Phil.",
"Philem.": "Philem.",
"Rev.": "Rev.",
"Rom.": "Rom.",
"Titus": "Tit."}
